version: "3"

services:
  hive-metastore:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-server:
    image: thisa08/hive:3.1.3.2
    ports:
      - 9083:9083
      - 10000:10000
    depends_on:
      - hive-metastore
