apiVersion: v1
appVersion: 3.1.3
description: The Apache Hive ™ data warehouse software facilitates reading, writing, and managing large datasets residing in distributed storage using SQL.
             Structure can be projected onto data already in storage. A command line tool and JDBC driver are provided to connect users to Hive.
home: https://hive.apache.org
icon: https://hive.apache.org/images/hive_logo_medium.jpg
maintainers:
- email: thisa08@gmail.com
  name: boffin
  url: http://github.com/thisadev
name: hive
sources:
- https://thisadev.github.io/boffin-labs/
- https://github.com/apache/hadoop
version: 1.0.1
