apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hive-server
  name: hive-server
spec:
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
    - name: "10000"
      port: 10000
      targetPort: 10000  
  selector:
    io.kompose.service: hive-server
status:
  loadBalancer: {}
