apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-metastore
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: hive-metastore
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: metastore_db
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_USER
              value: admin
          image: mariadb:latest
          name: hive-metastore
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
