apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hive-server
  name: hive-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: hive-server
    spec:
      containers:
      - name: hive-server
        image: thisa08/hive:3.1.3.2
        ports:
        - containerPort: 9083
        - containerPort: 10000
        - containerPort: 10002
        volumeMounts:
        - name: hadoop-config
          mountPath: /tmp/hadoop-config
          
        resources: {}

      restartPolicy: Always

      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-hadoop
status: {}
