apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hive-server
  name: hive-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: hive-server
    spec:
      containers:
        - image: thisa08/hive:3.1.3.2
          name: hive-server
          ports:
            - containerPort: 9083
            - containerPort: 10000
            - containerPort: 10002
          volumeMounts:
            - name: hadoop-config
              mountPath: "/tmp/hadoop-config"
              readOnly: true
          command:
            - "for f in slaves core-site.xml hdfs-site.xml mapred-site.xml yarn-site.xml; do \
               if [[ -e ${/tmp/hadoop-config/$f ]]; then \
                cp /tmp/hadoop-config/$f $HADOOP_HOME/etc/hadoop/$f \
               else \
                echo "ERROR: Could not find $f in /tmp/hadoop-config" \
                exit 1 \
               fi \
               done"
          volumes:
            - name: hadoop-config
              configMap:
                name: hadoop-hadoop

          resources: {}
      restartPolicy: Always
status: {}
